feat: add forest-night theme
casperstorm/ajour pull request #206
Opened 2020-10-07 03:38 UTC by jef

## Proposed Changes

- Adds [Forest Night](https://github.com/sainnhe/forest-night) theme

![image](https://user-images.githubusercontent.com/12074633/95284689-c6b0f080-082c-11eb-8155-6dbe733a1adf.png)

## Checklist

- [ ] Tested on all platforms changed
	- [x] Windows
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

2020-10-07 05:59 UTC, casperstorm requested changes
Hi jef,
Thanks for this PR. I would like you to take the screenshot. The one you have attached to this PR is just fine!

2020-10-07 05:59 UTC, casperstorm commented on CHANGELOG.md
> +- Forest Night theme
Since we aren't currently shipping themes with the binary we shouldn't add an entry to the `CHANGELOG.md`.

2020-10-07 13:59 UTC, jef commented
> I would like you to take the screenshot. The one you have attached to this PR is just fine!

Great! I'll do you one better when I get on my mac. Thanks!

2020-10-07 20:38 UTC, casperstorm commented
Lets go with Regular!

2020-10-08 05:19 UTC, casperstorm commented
@jef You should add an entry to THEMES.md as well 🙂 otherwise it looks ready to go.

2020-10-09 07:08 UTC, casperstorm commented
@jef take a look at https://github.com/casperstorm/ajour/pull/219.
I have been working on a refactor of the themes. I think it would make sense to work towards that with your theme instead. It will however require you add a few more colors but it will look better and we will ship Ajour with a set of themes and would love to have yours included.

Do you mind trying to redo towards the new system?

2020-10-09 15:34 UTC, jef commented
Yeah! Let's do it. What branch are you working on so I can see your changes and adjust.

2020-10-09 19:07 UTC, casperstorm commented
> Yeah! Let's do it. What branch are you working on so I can see your changes and adjust.

feat/refactor-color-themes

2020-10-09 21:26 UTC, casperstorm commented
@jef branch is ready now - you can see how we add the new pre-baked themes here: https://github.com/casperstorm/ajour/blob/feat/refactor-color-themes/crates/core/src/theme/mod.rs#L322-L345

2020-10-09 21:30 UTC, jef commented
Great! I'll make the changes and change the base ref to that branch.

2020-10-14 12:03 UTC, casperstorm commented
I've marked it as draft, until it is ready @jef.

2020-10-14 14:04 UTC, jef commented
> I've marked it as draft, until it is ready @jef.

Sorry and thank you. Works busy 🥲

2020-10-15 21:48 UTC, jef commented
@casperstorm, not sure if you like it, but I also moved the themes so that the Dark and Light are grouped at the top, Alliance and Horde are group second to top, and the rest are below -- all in lexicographical order. Not sure if you like that or not. If not, I can revert those changes and we can just keep `Forest Night`.

2020-10-16 09:59 UTC, casperstorm commented
@jef this is AWESOME.
I'll merge this. If you are looking for more work to do then I would love to get `monokai` theme as well eventually.
Or of you wanna dig deeper just let me know and we will find you a issue.

2020-10-16 10:03 UTC, casperstorm approved these changes

2020-10-16 10:04 UTC, merged